version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: remodely-crm-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: remodely-crm
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - remodely-network

  # Redis (Optional - for session management)
  redis:
    image: redis:7-alpine
    container_name: remodely-crm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - remodely-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: remodely-crm-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/remodely-crm?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - remodely-network

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: remodely-crm-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - remodely-network

volumes:
  mongodb_data:
  redis_data:

networks:
  remodely-network:
    driver: bridge
