services:
  # Backend API Service
  - type: web
    name: remodely-crm-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔨 Building Remodely CRM Backend..."
      npm ci --production=false
      npm run build
      echo "✅ Backend build complete!"
    startCommand: cd apps/backend && npm run start:prod
    healthCheckPath: /api/health
    autoDeploy: true # Auto-deploy enabled
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: remodely-crm-backend
          property: port
      - key: MONGODB_URI
        fromDatabase:
          type: mongodb
          name: remodely-crm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://crm-h137.onrender.com
      - key: CORS_ORIGINS
        value: https://crm-h137.onrender.com,https://remodely-backend-api.onrender.com
      - key: GOOGLE_REDIRECT_URI
        value: https://crm-h137.onrender.com/auth/google/callback
      # Performance optimizations
      - key: WEB_CONCURRENCY
        value: 2
      - key: MAX_OLD_SPACE_SIZE
        value: 460
      # Logging
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REQUEST_LOGGING
        value: true

  # Frontend Web Service
  - type: web
    name: remodely-crm-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔨 Building Remodely CRM Frontend..."
      npm ci --production=false
      npm run build
      # Ensure standalone bundle serves static & public assets (fixes manifest/icons 404)
      cd apps/frontend
      pwd && ls -la
      if [ -f "fix-standalone.sh" ]; then
        chmod +x ./fix-standalone.sh
        ./fix-standalone.sh
        echo "✅ Standalone assets fixed"
      else
        echo "⚠️ fix-standalone.sh not found"
      fi
      cd -
      echo "✅ Frontend build complete!"
    startCommand: cd apps/frontend && node .next/standalone/apps/frontend/server.js
    autoDeploy: true # Auto-deploy enabled
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: remodely-crm-frontend
          property: port
      - key: NEXT_PUBLIC_API_URL
        value: https://remodely-crm-backend.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://remodely-crm-backend.onrender.com
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://remodely-crm-backend.onrender.com
      - key: BACKEND_URL
        value: https://remodely-crm-backend.onrender.com
      # Performance optimizations
      - key: WEB_CONCURRENCY
        value: 1
      - key: MAX_OLD_SPACE_SIZE
        value: 460

databases:
  - name: remodely-crm-db
    databaseName: crm
    user: crmuser
