services:
  # Backend API Service
  - type: web
    name: remodely-crm-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      npm install
      cd apps/backend
      npm install
      npm run build
    startCommand: cd apps/backend && npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: remodely-crm-backend
          property: port
      - key: MONGODB_URI
        fromDatabase:
          type: mongodb
          name: remodely-crm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://remodely-crm-frontend.onrender.com
      - key: CORS_ORIGINS
        value: https://remodely-crm-frontend.onrender.com

  # Frontend Web Service  
  - type: web
    name: remodely-crm-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      npm install
      cd apps/frontend
      npm install
      npm run build
    startCommand: cd apps/frontend && node .next/standalone/apps/frontend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: remodely-crm-frontend
          property: port
      - key: NEXT_PUBLIC_API_URL
        value: https://remodely-crm-backend.onrender.com/api
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://remodely-crm-backend.onrender.com

databases:
  - name: remodely-crm-db
    databaseName: crm
    user: crmuser
